sudo: required
services: docker
language: minimal

script:
  - docker login -u $DOCKERUSER -p $DOCKERPASS
  - DOCKER_CONTENT_TRUST=1 docker build -t "bsycorp/kube-node-ready:latest" .
  - docker push bsycorp/kube-node-ready
