apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-node-ready
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-node-ready
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-node-ready
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-node-ready
subjects:
  - kind: ServiceAccount
    name: kube-node-ready
    namespace: kube-node-ready
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-node-ready
spec:
  replicas: 1
  template:
    metadata:
      namespace: kube-node-ready
      labels:
        app: kube-node-ready
    spec:
      containers:
        - name: kube-node-ready
          image: bsycorp/kube-node-ready:latest
          env:
          - name: NODE_TAINT
            value: "node.bsycorp.kubernetes.io/uninitialized"
          - name: DAEMONSETS
            value: "kube-system/kube-dns,kube2iam/kube2iam,kube-system/weave-net"
      serviceAccountName: kube-node-ready